### ISSUE TITLE
Support "shift lock" as an option instead of Caps Lock

### ISSUE THREAD

**Issue by GoogleCodeExporter** [klausw/hackerskeyboard#177]
```
Since v1.29, the keyboard uses Caps Lock/AutoCaps instead of the old Shift Lock 
behavior. This means that on most layouts, the 5th row now shows digits instead 
of !@#$% punctuation when in this mode.

Consider adding Shift Lock as an option for users who prefer the old behavior, 
for example:

- accessibility, Shift-Arrow selections are difficult without multitouch

- get number keys by default on the French AZERTY or similar keyboards that 
currently show uppercase accented chars on the 5th row
```

Original issue reported on code.google.com by `Klaus.We...@gmail.com` on 22 Jan 2012 at 3:58

**Comment by Kare999** [comment]
> ```
> Since v1.29, the keyboard uses Caps Lock/AutoCaps instead of the old Shift Lock 
> behavior. This means that on most layouts, the 5th row now shows digits instead 
> of !@#$% punctuation when in this mode.
> 
> Consider adding Shift Lock as an option for users who prefer the old behavior, 
> for example:
> 
> - accessibility, Shift-Arrow selections are difficult without multitouch
> 
> - get number keys by default on the French AZERTY or similar keyboards that 
> currently show uppercase accented chars on the 5th row
> ```
> 
> Original issue reported on code.google.com by `Klaus.We...@gmail.com` on 22 Jan 2012 at 3:58

Since v1.29, the keyboard uses Caps Lock/AutoCaps instead of the old Shift Lock 
behavior. This means that on most layouts, the 5th row now shows digits instead 
of !@#$% punctuation when in this mode.

Consider adding Shift Lock as an option for users who prefer the old behavior, 
for example:

- accessibility, Shift-Arrow selections are difficult without multitouch

- get number keys by default on the French AZERTY or similar keyboards that 
currently show uppercase accented chars on the 5th row
