### ISSUE TITLE
"Next" key

### ISSUE THREAD

**Issue by judsonw** [klausw/hackerskeyboard#606]
The next key is right next to the space bar and before the period.  This is a really bad placement for me. I find myself closing forms and moving to text regions inadvertently.  Can I remove it? I've looked through the instructions and didn't see anyway to remove annoying keys.

**Comment by TPS** [comment]
<kbd>⇥</kbd> is the Tab key.  None of the keys can be *re*moved, but using the standard 5-row keyboard (Options) will _move_ it elseplace.

**Comment by judsonw** [comment]
Yeah this key is insanely annoying. The five row is too small for my fingers. Using the 4 row I hit the tab key almost everytime I'm trying to hit the period. Its a shame.  The keyboard is almost perfect otherwise.

**Comment by TPS** [comment]
Did you try the last US QWERTY layout, the 5-row compact?  It looks like it's for your use-case.… 🤷‍♂️

**Comment by judsonw** [comment]
I've tried all of them in the three languages I use. They all seem to have this issue for me. I appreciate the assistance but I don't think it works for me.

**Comment by Barkuti** [comment]
The TAB key is a valuable tool to switch between input fields. In fact, it annoys me when due to app request the TAB key is missing.
I usually type on full 5-row layout standard view landscape with just 43% height and 0 automatisms, on a 4.5" screen device (XT1032 Moto G). I am not joking. Developing tapping SKILL is the real solution.

Cheers fellows 
![1040](https://user-images.githubusercontent.com/28562086/33056575-a764289c-ce86-11e7-8a6a-3283b8769416.gif)
