### ISSUE TITLE
Minor but irritating bug in Skype 

### ISSUE THREAD

**Issue by loadeddice** [klausw/hackerskeyboard#670]
In modern versions of Skype client for Android, HK doesn't function properly in nav mode; that is, arrow keys of the nav block are _all_ effectively treated as **Tab** key. Instead of moving along the text field, HK input focus slides through UI elements in the same order as if **Tab** key had been repeatedly pressed.

**Comment by klausw** [comment]
I don't think this is something I can fix, the keyboard is just sending keycodes to the app and it's up to the app to interpret them. If you have a Bluetooth keyboard, or a USB keyboard + a USB on-the-go adapter, you could try using a physical keyboard to check if that has the same issue.

FYI, the "GBoard" Google keyboard also has [arrow keys](https://www.xda-developers.com/gboard-v6-2-adds-cursor-control-cutcopypaste-buttons-and-adjustable-keyboard-dimensions/), have you tried if those have the same issue?

Closing for now, but let me know if you find evidence that this is really due to a keyboard bug.
