### ISSUE TITLE
Import/export xml layouts inside the app

### ISSUE THREAD

**Issue by ZeChArtiahSaher** [klausw/hackerskeyboard#725]
In reality, on vertical android mobile devices, I think such keyboard shines when one is uses it as a hybrid, something between the 4-row and 5-row compact.

4-row is quite useless and 5-row sometimes lacks functionality. 

So, I myself have modified xmls within apk to my liking and recompiled the app to rock a keyboard that I actually find useful. However, the process of either having to build the apk or recompile the apk every time is slow and old.

So, I propose as one of the last, final features, that I think would make this keyboard make more sense if the app had a simple import/export + create layout section. It doesn't even need to have UI. Just export xml, modify, import, reload.

This  is hacker's keyboard goddamit, but also it should hack usability not by building obsucure walls that one has to go climb in order to get something custom working. Isn't hacker's keyboard's point to give user the power of choice?

**Comment by klausw** [comment]
Importing/exporting XML is not easy, at least not when using the existing XML resource files. There's some complicated inheritance going on for the language-dependent strings, and AFAIK the resource XML files get precompiled into a binary representation for inclusion in the APK file.

Closing as "not feasible", I don't have any current plans to work on import/export of layouts.

FWIW, Hacker's keyboard's "point" was to make it easier to use Secure Shell on my Motorola Xoom tablet back in 2011. I've added some extra features since then and published it since other people found it useful also, but I don't have future ambitions to do anything specific with it. Sorry to disappoint...
