### ISSUE TITLE
ALL input data lost in 2 page document. Twice in an hour.

### ISSUE THREAD

**Issue by ckbeme** [klausw/hackerskeyboard#754]
I had not touched any special keys, none I'm aware of.
Is there a key that will Clear all typed info from a document? 
I tried ctrl Z which is Undo in Windows world. That did nothing.
I'm hoping there is a key that could cause this, and also a way to Undo that action.
I reentered as much info as I could recall, and the same thing happened again. This was in the sports Diaro Pro, a journal app I've been using for years. Please help. I'm going to have to go back to my old keyboard until I get an answer here.
 Also, whatever happened to cause all the data to be zapped... I'm curious if. Ctrl Z should function w Hackers keyboard just like in windows.  Or any of the common windows key combos, like Ctrl C, Ctrl V, Ctrl A, etc.
I love the keyboard, and had stopped using it because it's hard to use on cell phone. I recently got an Android Samsung tablet and I put Hackers KB on right away.
Thanks for any help.
 BTW, I have a clipboard mgr app and nothing was in clipboard.

**Comment by klausw** [comment]
There's no specific "clear all typed" key or function in the keyboard. In general it sends keystrokes to the app, and it's up to the app to interpret them. In general, I suspect that you may get the same issues if you were using a hardware keyboard.

People were hitting Ctrl-A by accident which is often interpreted as "select all", and then a following keystroke would replace the selected text. Current versions (>= 1.39.1) by default requires Ctrl-Alt-A to send a "Ctrl-A" keystroke, see https://github.com/klausw/hackerskeyboard/issues/487 .

Ctrl-Z for undo would also be up to the app or OS framework to implement. 

Do you have any idea which keys you might have been hitting? There's a recent related report about Tab key potentially causing data loss due to accidentally activating links: https://github.com/klausw/hackerskeyboard/issues/553

**Comment by ckbeme** [comment]
Thanks for your reply. I assume my Android version is possibly at the
current version or very close to current version.
Would you consider a Samsung Galaxy S7 Edge running Android v8 to be a
platform that your keyboard app can't handle?
I was typing in the alpha section most of the time. I would like for you to
dig a bit. I wonder if there is a sort of coincidence/connection to the
other case about a Tab key that was malfunctioning.

Please keep me in the loop on the Tab case too.

Thanks for your help and your great keyboard.

**Comment by klausw** [comment]
I don't think it's an issue of malfunctioning or not handling something.
The cases I mentioned is where the keyboard is acting as designed but not
as the user intended as a result of hitting the wrong key. The same thing
can happen on a desktop computer when misclicking or mistyping, though
arguably the risk is higher on a small phone screen where the keys are
closer together.

**Comment by ckbeme** [comment]
Thanks for your help
