### ISSUE TITLE
H

### ISSUE THREAD

**Issue by Jus71569** [klausw/hackerskeyboard#891]
**WARNING:** *This is a rather ancient project that was originally developed back in 2011 based on the Android 2.3 (Gingerbread) AOSP keyboard. While it still works as-is for many users, it would need some major rewrites to work with newer APIs, and some features such as language switching or popup keys don't work right on modern Android systems. I'm not currently planning on significant updates, and it's possible that it will stop working on modern devices or will no longer be updateable via the Google Play store due to minimum API level requirements. Play Store requires targeting API level 29 (Android 10), while the code was written for API level 9 (Android 2.3) from 2011.*

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 3]
 - OS: [e.g. Android 10]
 - App version [e.g. 1.41.1]

**Additional context**

**Comment by dever19aux** [comment]
i no longer use your piece of shit. stop emailing me you fuckiing
hacker. try to throw a football five yards.

**Comment by klausw** [comment]
On Sun, May 1, 2022, 22:40 dever19aux ***@***.***> wrote:

> i no longer use your piece of shit. stop emailing me you fuckiing
> hacker. try to throw a football five yards.


And a good day to you too. I am not emailing you. I would recommend
checking your GitHub settings to see if you're watching this repository,
since that would tell it to send you email for all issues being modified.
If that's the case, just unfollow the repository (and also any issues you
may be following individually) and enjoy the silence and additional time to
spend with your beloved football. Cheers!

**Comment by andrerodr** [comment]
Is there any Github bloopers?
This one deserved a place there.
