### ISSUE TITLE
WHERE THE FUCK IS THE GODDAMN CLIPBOARD!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by nodamnusername** [klausw/hackerskeyboard#954]
I JUST WROTE A WHOLE GODDAMN FUCKING BUNCH OF SHIT AND LOST IT ALL BECAUSE YOU, THE FUCKING GODDAMN DICKHEAD DEVELOPER DIDN'T PUT A GODDAMN CLIPBOARD UP IN THIS BITCH!!!!!!!!!!!!!!!!!!!!!!!!!

WHERE THA FOCK, IS THE GODDAMN THING!!!!!!!!!!!!!!!!!!!!

YOU FUCKING GODDAMN ASSHOLE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

I WROTE A WHOLE PAGE FULL OF STUFF!!!!!!!!!!!!!!!!!!!!!!!!!!!

ON FUCKING GODDAMN WIKIPEDIA!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

AND BECAUSE OF YOU NOT PUTTING A GODDAMN CLIPBOARD IN IT, I'VE LOST EVERYTHING I JUST TYPED!!!!

YOU GODDAMN FUCKING SON OF A BITCH!!!!!!!!!!!!!!!!!!!!!!!!!!

I COULD JUST FUCKING KILL YOU FOR THIS!!!!!!!!!!!!!!!!!!!!!!!!

GOD FUCKING DAMN YOU!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

HOW DARE YOU DO THIS TO ME WHEN I'M IN THE MIDDLE OF A GODDAMN FUCKING WIKIPEDIA EDIT!!!!!!!!!!!!

FUUUUUUUUCK YOUUUUUUUUUUUUUUUUUU!!!!!!!!!!!!!!!!!!!!!!

I COULD JUST FUCKING GODDAMN SMACK YOU UPSIDE THE HEAD FOR THIS FUCKING GODDAMN BULLSHIT!!!!!!!!!

WHAT THE FUCK!!!!!!!!!!!!!

WHERE'S THE GODDAMN CLIPBOARD!!!!!!!!!!!!!!!!!!!!!!!!!

YOU FUCKING GODDAMN SON OF A BITCH!!!!!!!!!!!!!!!!!!!!!!!!!!

I OUGHTTA REPORT YOUR GODDAMN ASS FOR THIS SHIT

HOW THE FUCK CAN YOU EVEN CALL THIS GODDAMN THING A KEYBOARD WHEN NO ONE CAN ACCESS THEIR FUCKING GODDAMN CLIPBOARD HISTORY!!!!!!!!!!!!!!!!!!!!!!!!!!

YA FUCKIN' IDIOT!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

THIS IS OBSURD!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

PUT THE FUCKIN' GODDAMN CLIPBOARD IN IT ALREADY!!

SHIT!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by ahmedosama1002** [comment]
Who the fuck are you to talk to me like that you son of a bitch I think you
got the wrong email you fucken bitch ass whore go get a life you sick son
of a bitch WTF are you talking about you noob ass nigga who the fuck you
think you are

**Comment by klausw** [comment]
@ahmedosama1002 , you most likely received this email due to being subscribed to updates for the hackerskeyboard GitHub project. See [here](https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/managing-subscriptions-for-activity-on-github/managing-your-subscriptions#unwatching-repositories) for unsubscribing instructions.

@nodamnusername , please read the text that was shown when you started filing this bug report, copied below. If you want clipboard history (which wasn't a thing back in 2011), I'd suggest using a different keyboard for your contributions to Wikipedia, though I'm unsure if your writing style is entirely compatible with their content guidelines. The app is unlisted on the Google Play store since it's not recommended for new users, and only remains there for people who specifically still want to continue using it despite its age.

> **WARNING:** *This is a rather ancient project that was originally developed back in 2011 based on the Android 2.3 (Gingerbread) AOSP keyboard. While it still works as-is for many users, it would need some major rewrites to work with newer APIs, and some features such as language switching or popup keys don't work right on modern Android systems. I'm not currently planning on significant updates, and it's possible that it will stop working on modern devices or will no longer be updateable via the Google Play store due to minimum API level requirements. Play Store requires targeting API level 29 (Android 10), while the code was written for API level 9 (Android 2.3) from 2011.*

**Comment by Vingolf** [comment]
Hallo @klausw,

Mit Hackerskeyboard hast du damals ein nützliches Tool erschaffen 👍 . 
Auf älteren Androidversionen läuft es gut,
 nur bei neueren Androidversionen funktioniert es nicht mehr so richtig.

Ich begrüße es, wenn deine App 
in einem Fork den aktuellen Anforderungen angepasst wird,
so wie möglicherweise hier:

• https://github.com/SeventhM/hackerskeyboard

Vielen Dank für Hackerskeyboard, es hat mir bisher gute Dienste geleistet 🙂 .

Vingolf
